### ISSUE TITLE
TypeError: Cannot read property 'sort' of undefined - version 0.6.2

### ISSUE THREAD

**Issue by heavyskyl** [ratherblue/eslint-html-reporter#17]
Node version: 11.7.0
OS: OSX Mojave
eslint version: 5.15.1

```javascript
TypeError: Cannot read property 'sort' of undefined
    at LintReporter.runReport (app/node_modules/eslint-html-reporter/src/js/lint-reporter.js:103:31)
    at module.exports (app/node_modules/eslint-html-reporter/reporter.js:11:27)
    at printResults (app/node_modules/eslint/lib/cli.js:92:20)
    at Object.execute (app/node_modules/eslint/lib/cli.js:209:17)
    at Object.<anonymous> (app/node_modules/eslint/bin/eslint.js:78:28)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
```

**Comment by ratherblue** [comment]
taking a look

**Comment by ratherblue** [comment]
forgot i renamed something, making a fix

**Comment by ratherblue** [comment]
Should be good to go now 👍

**Comment by heavyskyl** [comment]
Works well with v. 0.7.1. Thanks.
